name: My workflow

on:
  push:
    branches: [main, release]
  workflow_dispatch:

jobs:
  build:
    name: My build job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: |
        npm ci
        npm run build
        npm test
